# Generated by Django 6.0.1 on 2026-02-03 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("voluntarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Praticante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("responsavel", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("fila", "Fila de espera"),
                            ("ativo", "Em atendimento"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="fila",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "voluntario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="praticantes",
                        to="voluntarios.voluntario",
                    ),
                ),
            ],
        ),
    ]
